config/routes.rb
Rails.application.routes.draw do
  resources :entries

  devise_for :users
  root "pages#home"
  get "about" => "pages#about" # creates about path

end

app/models/entry.rb
class Entry < ActiveRecord::Base
	belongs_to :user

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	has_many :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  respond_to :html

  def index
    @entries = Entry.all
    respond_with(@entries)
  end

  def show
    respond_with(@entry)
  end

  def new
    @entry = current_user.entries.build
    respond_with(@entry)
  end

  def edit
  end

  def create
    @entry = current_user.entries.build(params[:entry])
    @entry.save
    respond_with(@entry)
  end

  def update
    @entry.update(params[:entry])
    respond_with(@entry)
  end

  def destroy
    @entry.destroy
    respond_with(@entry)
  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def correct_user
      @entry = current_user.entries.find_by(id: params[:id])
      redirect_to entries_path, notice: "Not authorized to edit this entry" if @entry.nil?
    end

    def entry_params
      params.require(:entry).permit(:description, :image)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/entries/_form.html.erb
<div class="container">
<div class="panel panel-default">
  <div class="panel-heading">
    <h2>New Entry</h2>
  </div>
  <div class="panel-body">
<%= form_for @entry, html: { multipart: true } do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>
</div>
</div>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<div id="entries" class="transitions">
  <h1>Listing entries</h1>
  <div class="box panel panel-default">
  <table>
    <thead>
      <tr>
        <<th>Image</th>
        <th>Description</th>
        <<th>User Email</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @entries.each do |entry| %>
        <tr>
          <td><%= image_tag entry.image.url(:thumb) %></td>
          <td><%= entry.description %></td>
          <td><%= entry.user.email if entry.user %></td>
          <td><%= link_to 'Show', entry %></td>
          <% if entry.user == current_user %>
          <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
          <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
 </div>
</div>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<%= image_tag @entry.image.url (:medium) %>

<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>

<%if @entry.user == current_user %>
	<%= link_to 'Edit', edit_entry_path(@entry) %> |
<% end %>
<%= link_to 'Back', entries_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Project IV", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>
          <% if user_signed_in? %>
              <% if user_signed_in? %>
               <li> <%= link_to 'New Entry', new_entry_path %> </li>
              <% end %>
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Log In", new_user_session_path %></li>
          <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Project IV</title>
  <%= stylesheet_link_tag	'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>

	<%= render "layouts/header" %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
	<%= yield %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1> About me </h1>
<p>I am a UNT Student working on my first Ruby app</p>

app/views/pages/home.html.erb
<div class="jumbotron">
<h1>Welcome to my Project IV Splashpage</h1>
<% if user_signed_in? %>
# do something
<% else %>
<p>
<%= link_to "Log in", new_user_session_path, class: "btn btn-primary btn-lg" %>
<%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>
<% end %>
</div>